// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdbeCU0pmv5675xYYuDV-OQg4z0ZmNDxs',
    appId: '1:866476346837:web:c1613bd360304873dc015c',
    messagingSenderId: '866476346837',
    projectId: 'focustime-18c30',
    authDomain: 'focustime-18c30.firebaseapp.com',
    storageBucket: 'focustime-18c30.firebasestorage.app',
    measurementId: 'G-PDQ60F8Z40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGrej5AdukbLyCtUIcLCHDqjFGthLW09Q',
    appId: '1:866476346837:android:9de49065de77325adc015c',
    messagingSenderId: '866476346837',
    projectId: 'focustime-18c30',
    storageBucket: 'focustime-18c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbikmtde9rcVz91xvufeifAC_lSWmFzoA',
    appId: '1:866476346837:ios:b66c85b8aa3aa203dc015c',
    messagingSenderId: '866476346837',
    projectId: 'focustime-18c30',
    storageBucket: 'focustime-18c30.firebasestorage.app',
    iosClientId: '866476346837-rbi7p4uq350od3e80ddp4gjjflammo9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbikmtde9rcVz91xvufeifAC_lSWmFzoA',
    appId: '1:866476346837:ios:b66c85b8aa3aa203dc015c',
    messagingSenderId: '866476346837',
    projectId: 'focustime-18c30',
    storageBucket: 'focustime-18c30.firebasestorage.app',
    iosClientId: '866476346837-rbi7p4uq350od3e80ddp4gjjflammo9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdbeCU0pmv5675xYYuDV-OQg4z0ZmNDxs',
    appId: '1:866476346837:web:5486dccc22a2e81ddc015c',
    messagingSenderId: '866476346837',
    projectId: 'focustime-18c30',
    authDomain: 'focustime-18c30.firebaseapp.com',
    storageBucket: 'focustime-18c30.firebasestorage.app',
    measurementId: 'G-5FMFL0PWV8',
  );
}
